### ISSUE TITLE
Show appropriate error message when scopes don't match

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#129]
For the Canvas API key we check the scopes from the Developer key console and also mention the scopes in the CCM [code base](https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/main/ccm_web/server/src/canvas/canvas.scopes.ts). 
When you miss checking the required scope currently logs it as `'State variable returned from Canvas did not match session ID; throwing unauthorized exception..` and from UI `You are not authorized to access this resource.` This is message is misleading and make you think something wrong with session data 

Steps to reproduce:
1. Go to Developer console and edit the API key scopes
2. don't chose the scopes that is mentioned in the [here](https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/main/ccm_web/server/src/canvas/canvas.scopes.ts)
3. Delete the your token from the `canvasToken` table and launch CCM
4. This should show you the error

**Comment by ssciolla** [comment]
I'll QA this.

**Comment by ssciolla** [comment]
This works as expected. Whenever a scope included in the application configuration (`canvas.scopes.ts`) is not included in the API Developer Key, a plain JSON error like this is shown:

```
{"statusCode":500,"message":"Canvas OAuth error encountered: \"A requested scope is invalid, unknown, malformed, or exceeds the scope granted by the resource owner. The following scopes were requested, but not granted: url:GET|/api/v1/courses/:course_id/assignments\"","error":"Internal Server Error"}
```

This isn't the most pretty error page, but we should only encounter this during configuration, and it does tell the user (administrator) exactly what the problem is.

Moving to Done.
