### ISSUE TITLE
Modify Course name color codes 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#151]
Comments from @janelilr 

![Screen Shot 2021-07-06 at 11 47 57 AM](https://user-images.githubusercontent.com/8579775/125303314-b5849b00-e2fa-11eb-900a-712d1098de82.png)
![Screen Shot 2021-07-06 at 11 47 43 AM](https://user-images.githubusercontent.com/8579775/125303335-b9b0b880-e2fa-11eb-8d75-77809f4caa6f.png)
 In regards to the above screenshot about the color difference in the course name title with and without edit roles, the color of text should be reversed. If a user is unable to edit, the text should be displayed in gray (indicates to users this cannot be changed). If a user can edit, the text would be black.

**Comment by ssciolla** [comment]
@pushyamig and @janelilr, I feel maybe this was fixed a while ago and the issue was never resolved. The current version of the code seems to have a disabled style when in non-editing mode, and a regular style when editing.

That said, I find it strange that what is supposed to be the page's header (or at least that's purpose it seems to serve to me) has a disabled style. In PR #241, I am proposing an alternative solution, where we use regular text in both cases, but the text in the non-editing case is an `h1`. I feel the absence of the text edit field underline is key enough that the text can't be edited until you click the button. Let me know your thoughts. I will add screenshots below.
![Screen Shot 2021-11-12 at 1 30 23 PM](https://user-images.githubusercontent.com/35741256/141517141-26c505f5-9990-400c-99f6-248c18e1c61e.png)
![Screen Shot 2021-11-12 at 1 30 39 PM](https://user-images.githubusercontent.com/35741256/141517144-3127848a-6adf-4bd3-a7bd-e78a848ce21c.png)

**Comment by pushyamig** [comment]
>I feel the absence of the text edit field underline is key enough that the text can't be edited until you click the button. Let me know your thoughts.

I will defer to @janelilr on this.

**Comment by janelilr** [comment]
> @pushyamig and @janelilr, I feel maybe this was fixed a while ago and the issue was never resolved. The current version of the code seems to have a disabled style when in non-editing mode, and a regular style when editing.
> 
> That said, I find it strange that what is supposed to be the page's header (or at least that's purpose it seems to serve to me) has a disabled style. In PR #241, I am proposing an alternative solution, where we use regular text in both cases, but the text in the non-editing case is an `h1`. I feel the absence of the text edit field underline is key enough that the text can't be edited until you click the button. Let me know your thoughts. I will add screenshots below.
> 
> **New version when not editing** ![Screen Shot 2021-11-12 at 1 30 23 PM](https://user-images.githubusercontent.com/35741256/141517141-26c505f5-9990-400c-99f6-248c18e1c61e.png)
> 
> **New version when editing** ![Screen Shot 2021-11-12 at 1 30 39 PM](https://user-images.githubusercontent.com/35741256/141517144-3127848a-6adf-4bd3-a7bd-e78a848ce21c.png)

@ssciolla The gray text was to indicate that it is currently inactive until you use the edit button. Is it possible to maintain the gray look until you edit the field, while still removing the underline in the-non editing case?

**Comment by ssciolla** [comment]
Thanks, @janelilr, I will treat this issue as resolved if/when my PR is merged.

**Comment by pushyamig** [comment]
Test passed!
