### ISSUE TITLE
Implement google analytics to track user metrics

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#161]
A new Google analytics Id need to be created for test/qa/prod, the global API call should be sending the GA ID to UI. 

This library is used by MyLA and ROHO as well https://github.com/react-ga/react-ga. We could use this but shop around if there is something better available as well

**Comment by jaydonkrooss** [comment]
Because our project uses typecript, I've found that I need to update the google analytics package to include types so that the import can be handled properly.  I'll create a new issue to create an index.d.ts file on that project.

Will try to imitate how the google analytics React Package structures its types: https://github.com/react-ga/react-ga/blob/master/types/index.d.ts
