### ISSUE TITLE
Incase of error view use Red exclamation

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#265]
Blue exclamation point icon used instead of the red exclamation point icon when alerting user. Use Red exclamation instead.

**Comment by lsloan** [comment]
Can you clarify?  The title says red, but the description seems to say blue would be better.  That seems contradictory and is confusing.

Remember that people with some kinds of color vision deficiency cannot distinguish between red and green.  If the idea to use red icons for errors is because other icons will be green for success, then the shape of the icons must represent the status clearly and the various ARIA attributes must be set.

**Comment by pushyamig** [comment]
Using the Red color is preferred than the Blue color.  This is a recommendation from @janelilr.
