### ISSUE TITLE
Add Non-UM User: include found user's name on the screen

### ISSUE THREAD

**Issue by melindakraft** [tl-its-umich-edu/canvas-course-manager-next#387]
When adding a non-UM user with the one at a time option and the user already exists, present that user's first and last name on the scree along with the "user found" message. This will help the tool user to make sure the external email address they entered was the right one and aligns with how the old CCM tool worked.

**Comment by ssciolla** [comment]
@show981111, here are the different steps I see for this problem:

1) Adjust the service and controller methods (and types) in `APIService` to return an object like this:
```
{
  loginId: string
  name: string
}
```
2) Change the return type in the frontend in `api.ts` so that it returns the new object.
2) Adjust the `AddNonUMUsers.tsx` component (and the necessary child components) so that the name is rendered.

**Comment by melindakraft** [comment]
Tested with existing user. Name was returned.
