### ISSUE TITLE
Include Override grade while converting the Canvas gradebook

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#86]
we have been converting the multi-column gradebook into a 2 column(uniqname and final grade). We always make sure that Current grade/Final grade column has same Letter grade and converted the Gradebook. But Canvas introduced Grade Override feature where users final grade is the grade in the `Override Grade` column. So in CCM Canvas Gradebook converter need to account for this when doing the conversion.

```
if( final_grade !== Current_grade && override_grade==FALSE){
      Validation fail // already happening but just that Overrride grade is not taken into effect 
}

if( final_grade !== Current_grade && override_grade==TRUE){
      student_grade = override_Grade // warn the user about the mis-match final and current grade
}
if( final_grade === Current_grade && override_grade==TRUE){
      student_grade = override_Grade 
}

```

So the final grade on the converted gradebook for a student should always be the override_grade if exist. 

Note that not all students grades will be overridden, even if the `Override Grade` column exits. So check needed for each student looking what their current_grade, final_grade is and if override_grade exists or not

Having a mismatched current/final grades and an override is an edge case. So, we warn the user that grade overrides are in the file so CCM is just going to take that grade.

[Sample Gradebook with override grade](https://github.com/tl-its-umich-edu/canvas-course-manager-next/files/6549416/2021-05-26T1226_Grades-Makraft_Test_Course_2021.csv)

**Comment by pushyamig** [comment]
@melindakraft I am assigning this issue to for a review, once you see confirm that the requirements are captured correctly. you can un assign yourself

**Comment by chrisrrowland** [comment]
Just want to confirm that treating grade mismatch as a warning instead of an error when override grade is present is the requirement.  That definitely requires some changes.

**Comment by melindakraft** [comment]
I'm happy to entertain your suggestions. We want to do what is easy
code-wise, but we recognize that one reason to use the override is
because faculty may use it to overcome the mismatch.

*Melinda Kraft, Service Manager for Learning Management*

*ITS Teaching & Learning*

131 Boyer Building, Ann Arbor, MI 48109-3704

734/763-0509 <+17347630509> | she, her, hers


*Need help with online instruction? Join the Teaching Online with Canvas
Workshops: From Good to Great!
<https://its.umich.edu/training/canvas> | Workshop Video Playlist
<https://www.mivideo.it.umich.edu/playlist/dedicated/137537371/1_bc51ybxg/1_fart74iy>*
